<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nexora Tech</title>
  <link rel="stylesheet" href="../styles/styles.css">
  <link rel="icon" type="image/png" href="../favicon/favicon.png">
</head>
<footer>
    <p>© 2025 Nexora Tech | Contact us: <a href="mailto:info@nexoratech.com">info@nexoratech.com</a></p>
    <p>Jira Project: 
      <a href="https://leminh.atlassian.net/jira/software/projects/SCRUM/boards/1" target="_blank">View our project here</a>
    </p>
    <p>GitHub Repository: 
      <a href="https://github.com/WebTechnologyProject-Sep2025/projectpart1-groupass1-1-cos10026-1-group-3" target="_blank">View our GitHub Repository here</a>
    </p>
  </footer>