<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Nexora Tech</title>
  <link rel="stylesheet" href="../styles/styles.css">
  <link rel="icon" type="image/png" href="../favicon/favicon.png">
</head>
<header class="navbar">
  <div class="logo">
    <img src="../images/logo.png" alt="Nexora Tech Logo">
  </div>
  <nav class="nav-links">
    <a href="index.php">Home</a>
    <a href="jobs.php">Jobs</a>
    <a href="apply.php">Apply</a>
    <a href="about.php">About Us</a>
  </nav>
</header>